name: dragonworkflow | shell script

on:
  push

jobs:
  Ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run bash script
        run: |
          chmod +x dragon.sh
          ./dragon.sh

      - name: Upload dragon file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt
