
name: dinafirstworkflow | shell script

on:
    push:
        branches: main
jobs:
    f_job:
        runs-on: ubuntu_latest
        steps:

            - name: checkout
              uses: actions/Checkout@v6.0.2

            - name: list files
              run : ls -ltra
 
            - name: run shell script
              run : 
                chmod +x myscript.sh
                 ./myscript.sh



